version: '3.9'

services:
  php:
    build: .
    volumes:
      - ".:/app"
      - "./php.ini:/usr/local/etc/php/php.ini"
    working_dir: /app

  nginx:
    image: nginx:1.17.0
    volumes:
      - ".:/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - "php"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mysql_data:/var/lib/mysql"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  mysql_data:
